export const steps = [
  {
    heading: "Pradėkime!",
    question: "Kada norėtumėte keliauti?",
    choices: ["Vasarą", "Rudenį", "Žiemą", "Pavasarį"],
    layout: null,
  },
  {
    heading: "Gerai!",
    question: "Kokia kelionės trukmė Jums aktuali?",
    choices: ["3 - 5 naktys", "6 - 9 naktys", "10 - 12 naktų", "14 ir daugiau"],
    layout: null,
  },
  {
    heading: "",
    question: "Kokia kryptis/šalis Jus domina?",
    choices: [
      "JAE",
      "Egiptas",
      "Graikija",
      "Juodkalnija",
      "Ispanija",
      "Turkija",
      "Tailandas",
      "Vietnamas",
      "Dominikos Respublika",
    ],
    layout: "grid",
  },
  {
    heading: "Pasitikslinkime detales",
    question: "Su kuo keliausite?",
    choices: ["Vienas (-a)", "Su partneriu", "Su šeima", "Su draugais"],
    layout: null,
  },
  {
    heading: "Gerai!",
    question: "Kokį biudžetą planuojate skirti kelionei?",
    choices: ["iki 700€ asm.", "iki 1000€ asm.", "virš 1000€ asm."],
    layout: null,
  },
  {
    heading: "Nuostabu!",
    question: "Pasirinkite viešbučio kategoriją",
    choices: ["4 - 5*", "2 - 3*", "1* ", "Apartamentai"],
    layout: null,
  },
  {
    heading: "Puiku!",
    question: "Kas Jums aktualu atostogų metu?",
    choices: [
      "Smėlėtas paplūdimys",
      "Diskoteka ir pramogos viešbutyje",
      "Ekskursijos / aktyvus poilsis",
      "Labiau orientuota į suaugusius",
      "Vandens kalneliai / parkai ",
      "Mini klubas ir kitos paslaugos vaikams",
      "Miestelis šalia viešbučio",
      "Sportas",
      "Elite viešbučiai",
    ],
    layout: "grid-two-col",
  },
];
